### ISSUE TITLE
The static login page does not load

### ISSUE THREAD

**Issue by temn** [flying-donut/flying-donut-operations#30] opened 2016-05-25 10:06 UTC
The static login page does not load on certain configurations. One reason is that AdBlocker Plus prevents loading of the login page on Chrome. In the other cases I have not yet figured out any reason. Any way it means that here is a design flaw which decreases the trust in the service.

**Comment by jtzikas** [comment] 2016-05-25 10:19
Do you have a screenshot to share on how the page looks like when you have the issue?

**Comment by temn** [comment] 2016-05-26 09:21
I have asked the student that experienced it to send me one.

**Comment by temn** [comment] 2016-05-28 07:47
This is what the screen looks like with ABP on.

![flying_donut_bug](https://cloud.githubusercontent.com/assets/10127868/15625967/53cbd98c-24eb-11e6-89b0-16a14942bd5a.PNG)

**Comment by jtzikas** [comment] 2016-06-01 14:21
We keep looking into the issue with no results so far. It is important to let you know that we don't serve any ads in our pages. The blocked indications you are getting are from Google Analytics api calls (containing "/ads/" in the uri) that are done from time to time. Those api calls are blocked but should not affect our service. We have been running the service with google chrome with AdBlocker Plus enabled for over a week and we could not reproduce the issue.

Do you know it the login page is blocked all the time or is broken randomly in few occasions?

**Comment by temn** [comment] 2016-06-04 15:58
I have now tested it a bit more myself. Every time that ABP is on the 
login function gets blocked. As soon as I remove or turn off ABP then it 
works. I cannot understand why yet.

**Comment by jtzikas** [comment] 2016-06-09 07:21
Could it be that there is a block element enabled? Could you check if you have custom filters in place that are blocking the login section (e.g. flying-donut.com##.hero.login). 

If not, then we have report it to ABP. According to their site (https://adblockplus.org/en/getting_started#false-positives) we have to report the issue from within ABP.

> Usually, this is not a bug in Adblock Plus but a problem with the filters (or filter subscription) you are using, these filters tell Adblock Plus to block something that shouldn't be blocked. You verify this by temporarily disabling Adblock Plus, if this "fixes" the problem you are dealing with a bad filter. Please report bad filters by using "Report issue on this webpage" feature that will automatically collect important data of the current web page: 

Since we can not reproduce the issue, we would like to ask you to report the issue for us.

**Comment by temn** [comment] 2016-06-10 06:16
My student checked the filter list. There is a filter list called "EasyPrivacy" that blocks the Flying Donut log in section. If he close it, then he can log in successfully. I have asked him to report it to ABP. Thank you for your help solving this issue.

**Comment by jtzikas** [comment] 2016-06-10 08:19
Great to see that the root cause is finally found. We where able to reproduce the issue and and we see that the filter blocks a required google analytics file to be loaded, that bring this part of the page down. We will prepare a fix and deploy it the soonest. 

Thank you for your great help.

**Comment by jtzikas** [comment] 2016-06-10 09:32
A fix has been deployed and tested on live. The issue has been resolved from our side. No need to send a bug report to the ABP now.

**Closed as completed** 2016-06-10 09:33 UTC
Labels: bug, fd:In Progress, fd:Done, fd:Approved
