### ISSUE TITLE
Action dropdown on a card does not allow any option to be selected because of the dropdown-backdrop element which takes up the entire screen

### ISSUE THREAD

**Issue by MadOgre** [flying-donut/flying-donut-operations#43] opened 2018-02-14 20:59 UTC
Tested in Chrome 64 and Firefox 58

**Comment by jtzikas** [comment] 2018-02-15 08:15
Hi,
I couldn't reproduce the issue on Chrome 64.0.3282.140 (64-bit) nor on Firefox 58.0.2 (64-bit) as shown the screenshots.

![image](https://user-images.githubusercontent.com/2730604/36246399-55b4f9ea-1238-11e8-9b25-c9f018c1ff71.png)

![image](https://user-images.githubusercontent.com/2730604/36246411-64b978d0-1238-11e8-9509-205bbe00b7cd.png)

Could you please let us know which OS you are using and if the issue persists after reloading the page?

**Comment by jtzikas** [comment] 2018-03-15 09:02
We are closing this issue since we couldn't reproduce it and we didn't hear back from you.

**Closed as completed by jtzikas** 2018-03-15 09:02 UTC
Labels: fd:Approved
